# Generated by Django 2.2 on 2021-02-06 14:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=700, null=True)),
                ('released_year', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', jsonfield.fields.JSONField()),
                ('genres', models.TextField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
