# Generated by Django 2.2 on 2021-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdata',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
