# Generated by Django 2.2 on 2021-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
